branches:
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
  
build_script:
  - qmake CopiesFinder.pro
  - mingw32-make
  
after_build:
  - windeployqt release/CopiesFinder.exe
  - rm release/*.o
  - rm release/*.cpp

#Note: artifacts path should be from root directory
artifacts:
  - path: release
    type: zip

deploy:
  release: myproduct-v$(appveyor_build_version)
  description:' '
  provider: GitHub
  auth_token:
    secure: e1K13ZmENgHItl5HRIuJJluDt975PLk9sXG9WG8yBs4uyXGQ7a0GOdAQ2uXhJuHi # your encrypted token from GitHub
  artifact: release.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
